05-01 20:23:01 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "WHEN" not found; SQL statement:
select * from todos order by when [42122-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Select.prepare(Select.java:808)
	at org.h2.command.Parser.prepareCommand(Parser.java:219)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1076)
	at reka.jdbc.JdbcQuery.run(JdbcQuery.java:93)
	at reka.jdbc.JdbcQuery.call(JdbcQuery.java:79)
	at reka.core.runtime.handlers.SyncAction.call(SyncAction.java:19)
	at reka.core.runtime.handlers.RuntimeNode.lambda$call$96(RuntimeNode.java:39)
	at reka.core.runtime.handlers.RuntimeNode$$Lambda$110/1708411309.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:744)
05-01 20:23:01 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "WHEN" not found; SQL statement:
select * from todos order by when [42122-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Select.prepare(Select.java:808)
	at org.h2.command.Parser.prepareCommand(Parser.java:219)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1076)
	at reka.jdbc.JdbcQuery.run(JdbcQuery.java:93)
	at reka.jdbc.JdbcQuery.call(JdbcQuery.java:79)
	at reka.core.runtime.handlers.SyncAction.call(SyncAction.java:19)
	at reka.core.runtime.handlers.RuntimeNode.lambda$call$96(RuntimeNode.java:39)
	at reka.core.runtime.handlers.RuntimeNode$$Lambda$110/1708411309.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:744)
05-01 20:32:23 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "0" for parameter "columnIndex" [90008-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:217)
	at org.h2.jdbc.JdbcResultSetMetaData.checkColumnIndex(JdbcResultSetMetaData.java:448)
	at org.h2.jdbc.JdbcResultSetMetaData.getTableName(JdbcResultSetMetaData.java:162)
	at reka.jdbc.JdbcQuery.handleResultSet(JdbcQuery.java:172)
	at reka.jdbc.JdbcQuery.run(JdbcQuery.java:110)
	at reka.jdbc.JdbcQuery.call(JdbcQuery.java:79)
	at reka.core.runtime.handlers.SyncAction.call(SyncAction.java:19)
	at reka.core.runtime.handlers.RuntimeNode.lambda$call$96(RuntimeNode.java:39)
	at reka.core.runtime.handlers.RuntimeNode$$Lambda$110/410045348.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:744)
05-01 20:32:25 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "0" for parameter "columnIndex" [90008-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:217)
	at org.h2.jdbc.JdbcResultSetMetaData.checkColumnIndex(JdbcResultSetMetaData.java:448)
	at org.h2.jdbc.JdbcResultSetMetaData.getTableName(JdbcResultSetMetaData.java:162)
	at reka.jdbc.JdbcQuery.handleResultSet(JdbcQuery.java:172)
	at reka.jdbc.JdbcQuery.run(JdbcQuery.java:110)
	at reka.jdbc.JdbcQuery.call(JdbcQuery.java:79)
	at reka.core.runtime.handlers.SyncAction.call(SyncAction.java:19)
	at reka.core.runtime.handlers.RuntimeNode.lambda$call$96(RuntimeNode.java:39)
	at reka.core.runtime.handlers.RuntimeNode$$Lambda$110/410045348.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:744)
05-01 20:35:04 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Value too long for column "NAME VARCHAR(40)": "'they just go into the same as the table name' (44)"; SQL statement:
insert into todos (name, done) values (?, false) [22001-173]
